version: '3.8'
services:
  app:
    restart: unless-stopped
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqlserver:3306/demo
      - SPRING_DATASOURCE_USERNAME=developer
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - mysqlserver
      - rabbitmq

  mysqlserver:
    image: 'mysql:latest'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE= demo
      - MYSQL_ROOT_PASSWORD=5350
        - MYSQL_USER=developer
        - MYSQL_PASSWORD=password
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db:/var/lib/mysql

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - "5673:5672"
      - "15673:15672"

volumes:
  db:

